# Generated by Django 2.2.2 on 2019-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BWZKMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bwzk', models.CharField(blank=True, max_length=4000, null=True)),
                ('archetype', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'teas_mapping_bwzk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din_277', models.CharField(blank=True, max_length=4000, null=True)),
                ('usage_zone', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'teas_mapping_din',
                'managed': True,
            },
        ),
    ]
