# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:20
from __future__ import unicode_literals

from django.db import migrations
from teaser_citydb.models import BWZKMapping
from teaser_citydb.models import UsageMapping


def bwzk_mapping_data(apps, schema_editor):
    """Write BWZK mapping from dict to database

    This mapping is according to PHD and simulation study of mla. However, in
    this study there where some differences. Especially if more then one BWZK
    are given the mapping is not identical.
    """
    bwzk_mapping = {
        "1300": "Office",
        "1300/2000": "Institute",
        "1300/2100": "Office",
        "1300/2220": "Institute4",
        "1300/2230": "Institute4",
        "1300/2230/2250": "Institute4",
        "1300/2230/7500": "Institute4",
        "1300/2250": "Institute4",
        "1300/2250/7300": "Institute4",
        "1300/2300": "Institute",
        "1300/7300": "Office",
        "1300/7300/7760": "Office",
        "1300/7500": "Office",
        "1300/7600": "Office",
        "1300/8000": "Office",
        "1350": "Office",
        "2000": "Institute",
        "2200": "Institute",
        "2220": "Institute4",
        "2230": "Institute4",
        "2230/2300": "Institute4",
        "2230/7300": "Institute4",
        "2240": "Institute4",
        "2250": "Institute4",
        "2300": "Institute",
        "3000": "Institute",
        "3200": "Institute",
        "4400": "SingleFamilyHouse",
        "5000": "SingleFamilyHouse",
        "6000": "SingleFamilyHouse",
        "6300": "SingleFamilyHouse",
        "6530": "SingleFamilyHouse",
        "7300": None,  # None ??
        "7300/7500": None,  # None ??
        "7500": None,  # None ??
        "7600": None,  # None ??
        "7700": None,  # None ??
        "7760": "Office",
        "8000": None,  # None ??
        "9130": "Office",
    }

    for key, value in bwzk_mapping.items():
        mapping = BWZKMapping(bwzk=key, archetype=value)
        mapping.save()


def din_mapping_data(apps, schema_editor):
    """Write BWZK mapping from dict to database"""
    din_mapping = {
        "NF1.1": "Living",
        "NF1.2": "Meeting, Conference, seminar",
        "NF1.3": "Meeting, Conference, seminar",
        "NF1.4": "Meeting, Conference, seminar",
        "NF1.5": "Laboratory",
        "NF2.1": "Group Office (between 2 and 6 employees)",
        "NF2.2": "Group Office (between 2 and 6 employees)",
        "NF2.3": "Meeting, Conference, seminar",
        "NF2.4": "Group Office (between 2 and 6 employees)",
        "NF2.5": "Group Office (between 2 and 6 employees)",
        "NF2.6": "Group Office (between 2 and 6 employees)",
        "NF2.7": "Group Office (between 2 and 6 employees)",
        "NF2.8": "Data center",
        "NF3.1": "Stock, technical equipment, archives",
        "NF3.2": "Stock, technical equipment, archives",
        "NF3.3": "Laboratory",
        "NF3.4": "Laboratory",
        "NF3.5": "Laboratory",
        "NF3.6": "Laboratory",
        "NF3.7": "Laboratory",
        "NF3.8": "Laboratory",
        "NF3.9": "WC and sanitary rooms in non-residential buildings",
        "NF4.1": "Stock, technical equipment, archives",
        "NF4.2": "Stock, technical equipment, archives",
        "NF4.3": "Kitchen in non-residential buildings",
        "NF4.4": "Kitchen in non-residential buildings",
        "NF4.5": "Stock, technical equipment, archives",
        "NF4.6": "Stock, technical equipment, archives",
        "NF5.1": "Meeting, Conference, seminar",
        "NF5.2": "Meeting, Conference, seminar",
        "NF5.3": "Meeting, Conference, seminar",
        "NF5.4": "Meeting, Conference, seminar",
        "NF5.5": "Stock, technical equipment, archives",
        "NF5.6": "Meeting, Conference, seminar",
        "NF5.7": "Meeting, Conference, seminar",
        "NF6.1": "Meeting, Conference, seminar",
        "NF6.2": "Meeting, Conference, seminar",
        "NF6.3": "Meeting, Conference, seminar",
        "NF6.4": "Meeting, Conference, seminar",
        "NF6.5": "Meeting, Conference, seminar",
        "NF6.6": "Meeting, Conference, seminar",
        "NF6.7": "Living",
        "NF6.8": "Meeting, Conference, seminar",
        "NF7.1": "WC and sanitary rooms in non-residential buildings",
        "NF7.2": "Meeting, Conference, seminar",
        "NF7.3": "Stock, technical equipment, archives",
        "NF7.4": "Stock, technical equipment, archives",
        "NF7.6": "Stock, technical equipment, archives",
        "NF7.7": "Stock, technical equipment, archives",
        "TF8.1": "Stock, technical equipment, archives",
        "TF8.2": "Stock, technical equipment, archives",
        "TF8.3": "Stock, technical equipment, archives",
        "TF8.4": "Stock, technical equipment, archives",
        "TF8.5": "Stock, technical equipment, archives",
        "TF8.6": "Stock, technical equipment, archives",
        "TF8.7": "Stock, technical equipment, archives",
        "TF8.8": "Stock, technical equipment, archives",
        "TF8.9": "Stock, technical equipment, archives",
        "VF9.1": "Traffic area",
        "VF9.2": "Traffic area",
        "VF9.3": "Traffic area",
        "VF9.4": "Traffic area",
    }

    for key, value in din_mapping.items():
        mapping = UsageMapping(din_277=key, usage_zone=value)
        mapping.save()


class Migration(migrations.Migration):

    dependencies = [("teaser_citydb", "0001_initial")]

    operations = [
        migrations.RunPython(bwzk_mapping_data),
        migrations.RunPython(din_mapping_data),
    ]
